tabWidth: 2
semi: false
singleQuote: true
trailingComma: all
plugins:
  - prettier-plugin-astro
overrides:
  - files: '.prettierrc'
    options:
      parser: json
  - files: '*.astro'
    options:
      parser: astro
